### ISSUE TITLE
Destroys media queries

### ISSUE THREAD

**Issue by corysimmons** [antonagestam/Squash#4]
``` python
>>> from squash import squash
>>> print squash("""
... .foo {
...   background: blue;
... }
... @media only screen and (min-width: 300px) {
...   .foo {
...     background: red;
...   }
... }
... .bar {
...   background: blue;
... }
... @media only screen and (min-width: 300px) {
...   .bar {
...     background: red;
...   }
... }
... """)
.foo, .bar {
background: blue;
}
 {
background: red;
}
```

See?

**Comment by antonagestam** [comment]
@corysimmons I have started working on a branch that recognizes different "scopes" and that would even merge different media queries if they're equal.

CSS animations with keyframes would also break the same way as you've described.

**Comment by corysimmons** [comment]
Have you considered http://www.reddit.com/r/webdev/comments/207ebb/squash_a_new_css_minifier/cg0j1ug ?
